# Generated by Django 4.2.7 on 2026-04-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('general', 'General Medicine'), ('emergency', 'Emergency'), ('cardiology', 'Cardiology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology'), ('gynecology', 'Gynecology'), ('surgery', 'Surgery'), ('other', 'Other')], max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_level', models.FloatField()),
                ('pain_scale', models.IntegerField()),
                ('ai_score', models.IntegerField(blank=True, choices=[(1, 'Immediate - Life Threatening'), (2, 'Emergency - Urgent'), (3, 'Urgent - Serious'), (4, 'Semi-Urgent'), (5, 'Non-Urgent - Minor')], null=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_action', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='apps.patient')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('triage_score', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='apps.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='apps.patient')),
            ],
            options={
                'ordering': ['triage_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('token_assigned', 'Token Assigned'), ('token_called', 'Token Called'), ('emergency', 'Emergency Alert'), ('general', 'General')], max_length=30)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apps.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.CharField(default='General Hospital', max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='apps.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='apps.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('escalated_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='apps.patient')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.token')),
            ],
            options={
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_patients', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='apps.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
