# Generated by Django 4.2.7 on 2026-04-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code used in queue e.g. general, cardiology', max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emergencyescalation',
            name='auto_escalated',
            field=models.BooleanField(default=False, help_text='True if created automatically from triage score'),
        ),
        migrations.AddField(
            model_name='emergencyescalation',
            name='triage_assessment',
            field=models.ForeignKey(blank=True, help_text='Auto-linked when created from triage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='apps.triageassessment'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='apps.department'),
        ),
        migrations.AlterField(
            model_name='token',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='apps.department'),
        ),
    ]
