# Generated by Django 4.2.7 on 2026-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_department_emergencyescalation_auto_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageassessment',
            name='ai_source',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('rule_based', 'Rule-Based Engine')], default='rule_based', help_text='Which engine produced this score', max_length=20),
        ),
    ]
